apiVersion: apps/v1
kind:  ReplicaSet
metadata: 
  name: rs
  labels:
    app: rpset
spec:
    selector: 
      matchExpressions:
        - {key: app, operator: In, values: [rpset]}
    replicas: 4
    template:
      metadata:
        labels:
          name: nginxapp
          app: rpset
      spec:
        containers:
          - name: nginxapp
            image: nginx:latest 
            ports:
                - containerPort: 80
                  protocol: TCP